### ISSUE TITLE
Medicine prescription 

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#10]
# User story
Als Therapeut möchte ich eine Medikamentenverschreibung für einen Patienten erfassen können.

# Akzeptanzkriterien
- [x] Ein Therapeut kann eine neue Verschreibung hinzufügen.
- [x] Ein Therapeut kann eine Verschreibung bearbeiten.
- [x] Eine Verschreibung enthält das Medikament.
- [x] Eine Verschreibung enthält, wie oft das Medikament eingenommen werden muss.
- [x] Eine Verschreibung enthält, welche Dosis eingenommen werden muss.
- [x] Eine Verschreibung zeigt den Start- und Endpunkt ihrer Gültigkeit.

# Tasks
- [x] #47 
- [x] #48 
- [x] #49
