### ISSUE TITLE
Activity Diary

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#11]
# User story
Als Patient möchte ich meine letzten Aktivitäten verfolgen können.

# Akzeptanzkriterien
- [x] Ein Patient hat ein Tagebuch seiner Aktivitäten.
- [x] Ein Patient kann seine Aktivitäten kategorisieren.
- [x] Ein Patient kann seinen Aktivitäten eine Text-Beschreibung hinzufügen.

# Tasks
TBD
