### ISSUE TITLE
Therapist Emergency Calls

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#15]
# User story
Als Patient in einer Notfallsituation möchte ich meinen Therapeuten anrufen können und ihm um seinen Ratschlag fragen können.

# Akzeptanzkriterien
- [x] Jeder Patient kann die Kontaktinformationen seines Therapeuten aufrufen.
- [x] Ein Patient kann über einen einfachen Weg seinen Therapeuten anrufen.

# Vorbedingungen
- [x] #18 Assigned Therapist

# Tasks
- [x] #46 Übersichtsseite für Notfallnummern
