### ISSUE TITLE
General Emergency Calls

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#16]
# User story
Als Patient in einer Notlage möchte ich einen Anruf an eine Notrufnummer tätigen können.

# Akzeptanzkriterien
- [x] Multiple hotlines are available in the system.
- [x] A Patient may call one of the hotlines using a button

# Tasks
- [x] #46 Übersichtsseite für Notfallnummern
