### ISSUE TITLE
Specialist Chat

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#17]
# User story
As a medical specialist or patient, I want to be able to chat with my patient / specialist.

# Acceptance criteria

- [ ] Patients know the medical specialist, who is assigned to them.
- [ ] Medical specialists know the patients, that are assigned to them.
- [ ] Patients may open a chat with their medical specialist.
- [ ] Medical specialists may open a chat with one of their patients.
- [ ] The user gets notified if he receives a new chat message

# Tasks
TBD
