### ISSUE TITLE
Assigned Therapist

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#18]
# User story
Als Patient möchte ich sehen, welcher Therapeut mir zugewiesen ist.

# Akzeptanzkriterien
- [x] Der Patient kennt den ihm zugewiesenen Therapeuten.
- [x] Der Patient kann die Kontaktinformationen seines Therapeuten einsehen.

# Tasks
- [x] #23 UI für zugewiesener Therapeut
- [x] #52 Korrekte Anzeige des zugewiesenen Therapeuten

# Aufwand
Geschätzt: 4h (davon 1h Testing)
