### ISSUE TITLE
Patient List

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#19]
# User story
As a medical specialist, I want to know the patients assigned to me.
Als Therapeut möchte ich alle mir zugewiesenen Patienten sehen.

# Akzeptanzkriterien

- [x] Der Therapeut kennt die ihm zugewiesenen Patienten.
- [x] Der Therapeut kann die Kontaktinformationen der ihm zugewiesenen Patienten einsehen.

# Vorbedingungen
- [x] #8 User Registration

# Tasks
- [x] #26 UI für zugewiesene Patienten
- [x] #40 Zugewiesene Patienten werden optisch falsch aufgelistet
- [x] #53 Korrekte Anzeige der zugewiesenen Patienten

# Aufwand
Geschätzt: 4h (davon 1h Testing)
