### ISSUE TITLE
Calendar per Person

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#2]
# User story
As a user of the PMS, I want to have a calendar, so I can manage my appointments.

# Acceptance criteria

- [ ] Each Person has its own calendar
- [ ] Appointments can be added to the calendar
- [ ] Appointments can be deleted from the calendar

# Tasks
TBD
