### ISSUE TITLE
Kontaktinformationen pflegen

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#25]
# User story
Als Benutzer von PMS will ich meine Kontaktinformationen pflegen und aktuell halten können.

# Akzeptanzkriterien

- [x] Kontaktdaten können vom Benutzer gepflegt werden.
- [x] Kontaktdaten werden in der Datenbank abgelegt.

# Tasks

- [x] #24 Benutzer selbstverwaltung erstellen 

# Aufwand
Geschätzt: 4h (davon 1h Testing)
