### ISSUE TITLE
Appointment requests

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#3]
# User story
As a user of PMS, I want to send a request for an appointment to another user.
As recipient of an appointment request, I want to be able to accept or reject the appointment.

# Acceptance criteria

- [ ] Requests an appointment may be sent to another user
- [ ] An appointment request may be accepted
- [ ] An appointment request may be rejected

# Tasks
TBD
