### ISSUE TITLE
GUI Design

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#32]
# User story
Als Benutzer von PMS will ich eine Startseite zu der Applikation haben.

# Akzeptanzkriterien

- [ ] Sobald ein Benutzer eingeloggt ist, wird ihm die Startseite angezeigt.
- [ ] Die Startseite bietet Links zu allen weiteren Seiten.
- [ ] Auf der Startseite werden wichtige Nachrichten angezeigt (z.B. Chatnachrichten, Medikamenten-Benachrichtigungen, ...).

# Tasks
1. - [ ] #31 Design Landing Page 

# Aufwand
Geschätzt: 5h (davon 1h Testing)

**Comment by siebl** [comment]
Dies ist keine Userstory
