### ISSUE TITLE
Chatübersicht für Therapeuten

### ISSUE THREAD

**Issue by faebuk** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#42]
# User story
Als Therapeuten brauche ich eine Übersicht aller meiner Chats mit meinen Patienten. 
Da ich mehrere Patienten habe und nicht zwingend mit jedem einen Chat schon habe, soll als Übersicht alle Patienten angezeigt werden. Falls man auf einen Patienten klickt, wird der entsprechende Chat geöffnet. Falls noch nicht vorhanden, wird ein leerer mit dem Patienten erstellt.

# Akzeptanzkriterien

- [x] Übersicht aller Patienten
- [x] Neuer Chat wird erstellt, falls man auf Patient klickt und noch nicht vorhanden
- [x] Chat wird geöffnet, falls man auf Patient klickt und Chat schon vorhanden ist

# Aufwandsschätzung
Geschätzter Aufwand: 4h

# Tasks
- [x] #43
