### ISSUE TITLE
Information about condition

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#5]
# User story
As a medical specialist, I want to be able to provide information about the different diagnoses, so patients may inform themselves about their condition.

# Acceptance criteria

- [ ] A medical specialist may create new informational pages for patients.
- [ ] A medical specialist may edit an informational page.
- [ ] A Patient may access different informational pages.

# Tasks
TBD
