### ISSUE TITLE
Mood Diary

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#6]
# User story
Als Patient möchte ich meine Stimmungen in einem Tagebuch erfassen können.

# Akzeptanzkriterien
- [x] Ein Patient hat ein Stimmungstagebuch.
- [x] Ein Patient kann eine Beschreibung für seine Stimmung hinzufügen.

# Tasks
- [x] #54 UI für Stimmungstagebuch (Neuer Eintrag)
