### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#8]
# User story
Als Therapeut möchte ich neue Patienten erfassen können.

# Akzeptanzkriterien
- [x] Therapeuten können neue Patienten erfassen.
- [x] Patienten können sich nicht selber erfassen.

# Tasks
- [x] #20 Tabelle zum Speichern von Benutzern 
- [x] #22 Datenbank initialisieren
- [x] #21 UI für neuen Patienten erfassen
- [x] #39 Neuen Patienten registrieren: Passwort setzen

# Aufwand
Geschätzt: 11h (davon 2h Testing)
