### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#9]
# User story
Als Benutzer möchte ich mich am System anmelden können.

# Akzeptanzkriterien
- [ ]Therapeuten können sich am System anmelden.
- [x] Patienten können sich am System anmelden.
- [x] Das Passwort wird geprüft.

# Tasks
- [x] #27 Login 

# Aufwand
Geschätzt: 4h (davon 1h Testing)
